# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ded0e7a52401f7c2392739ce828f5ac1b099b84041443666e0a5715b33812c099553ca2664f23e23fde1f5d1a58575d3f8ed73a9115913f5d9159e7d777bb8a

test:
  secret_key_base: 67bb2de0a546676391edeeef6a241535921def241f39738b0e0459a9888c8adef719b00df7a5ede9de32e111e362fd4d7f52b415ba79bc65100857c52c5a68c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
